### ISSUE TITLE
No autocomplete for basic syntax

### ISSUE THREAD

**Issue by mbalazy** [kristijanhusak/vim-dadbod-completion#10]
Ok so, I'm a totaly noob in sql but why there is no sugestions for just normal sql syntax like if readme gif?
I don'y have _select_, _from_ etc. syntax, just a column name sugestions. What soould I do to enable it?

Im using vim-dadbod, instaled from coc, macOS.

![Screenshot 2020-10-09 at 16 10 13](https://user-images.githubusercontent.com/49127168/95593630-39e37e00-0a4a-11eb-98ba-0c49ef6fed9e.jpg)
![Screenshot 2020-10-09 at 16 10 00](https://user-images.githubusercontent.com/49127168/95593641-3b14ab00-0a4a-11eb-80bf-b273aedb082f.jpg)

**Comment by kristijanhusak** [comment]
in Gif you see that because that comes from "tags" source, or something like that. It is not from `vim-dadbod-completion`. This plugin gives you autocompletion for tables and columns.
