### ISSUE TITLE
 Invalid expression: ]} errors pop up when start up neovim @manjaro 

### ISSUE THREAD

**Issue by soulspirits** [kristijanhusak/vim-dadbod-completion#15]
line   73:
E15: Invalid expression: ]}
E15: Invalid expression: {   'sql': [    {'complete_items': ['vim-dadbod-complet
ion']},   ], ]}
Press ENTER or type command to continue

**Comment by kristijanhusak** [comment]
Readme had a bad syntax for completion-nvim setup. Replace it with this:
```vim
let g:completion_chain_complete_list = {
    \   'sql': [
    \    {'complete_items': ['vim-dadbod-completion']},
    \   ],
    \ }
```

**Comment by soulspirits** [comment]
> Readme had a bad syntax for completion-nvim setup. Replace it with this:
> 
> ```viml
> let g:completion_chain_complete_list = {
>     \   'sql': [
>     \    {'complete_items': ['vim-dadbod-completion']},
>     \   ],
>     \ }
> ```

it works!
