### ISSUE TITLE
not working with compe?

### ISSUE THREAD

**Issue by alex-popov-tech** [kristijanhusak/vim-dadbod-completion#19]
hey, thanks for the plugin!
I saw your config  https://github.com/kristijanhusak/neovim-config/blob/bleeding-edge/nvim/lua/partials/completion.lua#L18 and tried to do the same:
```
return function()
    require "compe".setup {
        enabled = true,
        autocomplete = true,
        debug = false,
        min_length = 1,
        preselect = "enable",
        throttle_time = 80,
        source_timeout = 200,
        incomplete_delay = 400,
        max_abbr_width = 100,
        max_kind_width = 100,
        max_menu_width = 100,
        documentation = true,
        allow_prefix_unmatch = true,
        source = {
            path = {menu = " "},
            buffer = {menu = " "},
            vsnip = {menu = " "},
            nvim_lsp = {menu = "  "},
            nvim_lua = {menu = " "},
            spell = true,
            calc = true,
            tags = true,
            -- omni = true,
            vim_dadbod_completion = true,
            treesitter = true
        }
    }
    map("i", "<cr>", 'compe#confirm("<cr>")', {silent = true, expr = true})
    -- map("i", "<s-cr>", "compe#complete()", {silent = true, expr = true})
end
```

but with that when typing in query buffer i see nothing from dadbod completion :(

**Comment by kristijanhusak** [comment]
Did you set up `g:db` or `b:db` variable for vim-dadbod?

**Comment by alex-popov-tech** [comment]
nope, setting up db through env vars

**Comment by kristijanhusak** [comment]
Are you using [vim-dadbod-ui](https://github.com/kristijanhusak/vim-dadbod-ui)  ?

**Comment by alex-popov-tech** [comment]
yes

**Comment by kristijanhusak** [comment]
Is everything working fine in dadbod ui? Do you see tables and everything?

**Comment by alex-popov-tech** [comment]
![image](https://user-images.githubusercontent.com/21224705/110385233-5fab9800-8067-11eb-879b-4fa0d1b56044.png)

**Comment by kristijanhusak** [comment]
post me your compe config.

**Comment by alex-popov-tech** [comment]
fist comment?

**Comment by kristijanhusak** [comment]
Sorry, didn't saw it. I see that you use sqlite. It is not so well supported. It autocompletes only reserved words and tables.

I just pushed a fix, it should be working now.

**Comment by kristijanhusak** [comment]
Subscribe to [this](https://github.com/kristijanhusak/vim-dadbod-completion/issues/21) issue if you want to follow updates on sqlite. I plan to add a bit better support (table + column completion), but I'm not sure when I'll get to it.

**Comment by alex-popov-tech** [comment]
thanks! better now
