### ISSUE TITLE
Lag when pressing dot character in sql file

### ISSUE THREAD

**Issue by RRikor** [kristijanhusak/vim-dadbod-completion#22]
Thank you for the great plugin! 

Unfortunately i'm experiencing some lag when using a combination of nvim-compe and vim-dadbod-completion. It happens when i'm in an sql file and type a dot '.' character. I ran a profile and some functions of vim-dadbod-completion are being triggered 10212 times. That would explain the huge size of the intellisense list after pressing that dot.  Is there some way to limit the amount of things being loaded in the intellisense list? Or is this caused by nvim-compe? I'm unsure what is causing this.

NVIM v0.5.0-dev+1294-gad8114444 
Build type: Debug

vim-dadbod-completion and nvim-compe both up to date.

Attaching the profile.log and the nvim-compe.vim configuration to the ticket.
[compe.txt](https://github.com/kristijanhusak/vim-dadbod-completion/files/6439751/compe.txt)
[profile.log](https://github.com/kristijanhusak/vim-dadbod-completion/files/6439718/profile.log)

**Comment by kristijanhusak** [comment]
Hi @RRikor,

how big is your database? 10212 is the number of results that are being mapped, that's why you see 10212 entries in there.
I agree it's big and it should be optimized.

Can you tell me if you just type the `.` or you type something before it?

For example, do you get lag when you type something like this:
```sql
select * from posts.
```

Or you just type the dot and get the lag?
```sql
.
```

**Comment by RRikor** [comment]
Hi @kristijanhusak,

Thank you for the quick reply! And thanks for the tip! The lag was happening when I pressed the dot and when I pressed the schemaname+dot. In both occasions.

I am writing tables for a new schema in a PostgreSQL database. The schema is currently empty.  So I guess if
the plugin can't find the schema, or when the schema is empty, it loads all results from pg_tables.tablename + some other pg_ tables into the list?
  
I created a dummy table in the schema and now it only displays that dummy table when using schemaname+dot. So the lag is gone :-)

Though it would be nice if it would limit the results in the list somehow. Apparently the maximum number of columns in PostgreSQL is 1600. https://www.postgresql.org/docs/current/limits.html

Thanks for the help!

**Comment by kristijanhusak** [comment]
@RRikor I introduced a limitation for each source returned to 50. If you pull latest master, it should be working better for you.
If you want to configure limits follow the [docs](https://github.com/kristijanhusak/vim-dadbod-completion/blob/master/doc/vim-dadbod-completion.txt#L99)

Let me know if it's better.

**Comment by RRikor** [comment]
Perfect! Thanks very much for the quick fix!
