### ISSUE TITLE
Customize menu for nvim-cmp source display

### ISSUE THREAD

**Issue by CarbonChauvinist** [kristijanhusak/vim-dadbod-completion#26]
Using nvim-cmp as completion engine and am trying to customize the display of the vim-dadbod-completion source. 

I've seen your [issue](https://github.com/hrsh7th/nvim-cmp/issues/98) opened with nvim-cmp , and from what I understand of the exchange it should be possible as long as I explicitly set this up using formatting table within cmp? 

My relevant setup is as follows:
```
~/.config/nvim/lua/plugins.lua
...
  use({
    "kristijanhusak/vim-dadbod-ui",
    config = [[require("dadbodui")]],
    requires = {
      { "tpope/vim-dadbod" },
      {
        "kristijanhusak/vim-dadbod-completion",
        config = function()
          vim.cmd(
            [[autocmd FileType sql,mysql,plsql lua require("cmp").setup.buffer({sources = {{ name = "vim-dadbod-completion" }, { name = "buffer" },} })]]
          )
        end,
      },
    },
  })
...
```
```
~/.config/nvim/lua/mycmp.lua
...
  formatting = {
    format = function(entry, vim_item)
      vim_item.menu = ({
        nvim_lsp = "[LSP]",
        buffer = "[BFR]",
        path = "[PTH]",
        nvim_lua = "[LUA]",
        vim_dadbod_completion = "[DB]",
      })[entry.source.name]
      return vim_item
    end,
  },
})
...
```
But I still only have `TEXT` listed as the completion source.

I guess my question is what is the correct way of manually assigning this? I know you use `-` in the name, but the vim_item does not accept those so I changed to `_`. I'm sure I'm missing something obvious, can you provide any insight please?

**Comment by kristijanhusak** [comment]
Property name is wrong, it needs to use `-` instead of `_`. Like this:
```lua
  formatting = {
    format = function(entry, vim_item)
      vim_item.menu = ({
        nvim_lsp = "[LSP]",
        buffer = "[BFR]",
        path = "[PTH]",
        nvim_lua = "[LUA]",
        ['vim-dadbod-completion'] = "[DB]",
      })[entry.source.name]
      return vim_item
    end,
  },
})
```

If you are adding this `format` function only because of this plugin, there's no need. If you completely remove this function it should still provide it as `Text [DB]`.

**Comment by CarbonChauvinist** [comment]
Thanks! Yes using ` ['vim-dadbod-completion'] = "[DB]",` as the entry cleared the issue up for me and it is now showing `Text [DB]` as the completion source.

And I'm not adding the format function for only your plugin -- I actually mainly wanted to customize the menu for *other* sources, but it appears that if customizing other sources the default `[DB]` from this plugin is no longer passed along and you have to explicitly add it instead.

This is resolved for me now -- thanks again.

**Comment by kristijanhusak** [comment]
Great! Yeah, this `format` function overrides the built in. Closing.
