### ISSUE TITLE
How to set this with cmp and lua based config?

### ISSUE THREAD

**Issue by thepenguinthatwants** [kristijanhusak/vim-dadbod-completion#31]
I created 
`~/.config/nvim/ftplugin/sql.vim file`
and added

" hrsh7th/nvim-cmp
`  autocmd FileType sql,mysql,plsql lua require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })`

But it doesn't seem to do anything. Wondering what's the recommended way to add this?

**Comment by kristijanhusak** [comment]
you should not use `autocmd` in the `ftplugin` file. This should be sufficient in there:
```vim
lua require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })
```

**Comment by thepenguinthatwants** [comment]
Thanks for the reply and it works!!

**Comment by zer09** [comment]
@kristijanhusak sorry to chime in, but I cant make this work I am using Packer for the package manager and have this

```lua
 -- Sql
use "tpope/vim-dadbod"
use { "kristijanhusak/vim-dadbod-completion" }
use { "kristijanhusak/vim-dadbod-ui" }
```

and this
```lua
vim.cmd([[
  augroup DadbodSql
    au!
    autocmd FileType sql,mysql,plsql lua require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })
  augroup END
]])

-- also tried this without vim.cmd
require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })
```

It works on DBUI, but I cant make it work on directly on sql files

**Comment by kristijanhusak** [comment]
@zer09 did you set `g:db` or `b:db` ? https://github.com/kristijanhusak/vim-dadbod-completion#how-it-works

**Comment by zer09** [comment]
Yes, but it will only autocomplete if I open the buffer using the `New query` from the `DBUI`.
I have existing sql file scripts, it just kinda works I mean not working properly. example there is no completion for the table name or it just keep suggesting this two irrelevant tables. to get the completion for the columns I need to type the table name followed by the dot before it will suggest the columns.

But using dbui it works perferctly fine

**Comment by kristijanhusak** [comment]
I need to check. Can you please open up separate issue for that?
