### ISSUE TITLE
Completion from multiple databases

### ISSUE THREAD

**Issue by bowmanjd** [kristijanhusak/vim-dadbod-completion#34]
I am unsure if this is a feature request, or a need for better understanding on my part... Thus far, I only get completion of table names and columns from the database specified in the connection. But when I `SELECT FROM OtherDatabase.dbo.OtherTable` I do not see completion suggestions.

Is this by design, or am I doing something wrong?

I am using a sqlserver connection.

If this is by design, might you consider adding this feature? Or perhaps this would be a feature added to vim-dadbod?

**Comment by dm19** [comment]
It seems like there are three options: pulling in completions from all databases on a server, keeping multiple database connections to pull completions from, or switching the current database for the buffer. 

The first one I think is obviously a bad idea. 

The other two I think probably belong best in dadbod-ui (or maybe another small plugin that would support both dadbod and dodbod-ui?). Creating a function to switch the connection for the current buffer would probably be simple to implement though it would still require manual switching, which isn't perfect. Something like a workspace feature that could send vim-dadbod-completion multiple database connections to complete from should make completing from multiple databases seamless, but would require a good deal more work from both plugins.

**Comment by bowmanjd** [comment]
Sounds like this issue is best solved over at dadbod-ui.

**Comment by fingolfin19** [comment]
Dadbod-ui already allows for multiple active connections. I think to get multiple database completion working the changes need to be made here.

- If not using dadbod-ui, no changes.
- If using dadbod-ui get all active database connections for the same server that the current buffer is connected to
- Add database key to the cache
- Query each active database connection and for each add all schemas/tables/columns etc. to the cache

Am I missing anything big?
