### ISSUE TITLE
Getting 'using Dictionary as String' error

### ISSUE THREAD

**Issue by peteryates** [kristijanhusak/vim-dadbod-completion#4]
Firstly, thanks for this tool, it worked perfectly the first time I tried it. Now, however, I'm encountering this problem. In PostgreSQL, every time I try to complete, I get this error:

```
Error detected while processing function coc#_complete:
line    3:
E731: using Dictionary as a String
Press ENTER or type command to continue
```

This happens both when Coc is enabled and disabled using using omnicompletion (having set `:setlocal omnifunc=vim_dadbod_completion#omni`).

I'm using PostgreSQL 12.2 with [this database](https://github.com/DFE-Digital/gias-query-tool) and neovim 0.4.3. All the plugins are up to date and loaded via Pathogen.

One thing to note, the completion _does_ still appear to work but input is interrupted by the error message flashing up after every keystroke.

![Screenshot from 2020-05-03 12-36-17](https://user-images.githubusercontent.com/128088/80913228-f9fdc980-8d3a-11ea-94d9-e19bc59b0470.png)

Please let me know if you need any more info.

**Comment by kristijanhusak** [comment]
Ah, yeah, I didn't consider incompatibilities between coc and completion-nvim. Do an update and give it another test, should be working now.

**Comment by peteryates** [comment]
Worked perfectly, thank you so much :+1:
