### ISSUE TITLE
autocompletion with nvim-cmp now emits E730: using List as a String

### ISSUE THREAD

**Issue by bowmanjd** [kristijanhusak/vim-dadbod-completion#40]
While editing a SQL file, when attempting to autocomplete fields (for instance, I type `TableName.` then any letter) I get the following error:

```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: Vim(call):E730: using List as a String
stack traceback:
        [C]: in function 'vim_dadbod_completion#omni'
        ...tart/vim-dadbod-completion/lua/vim_dadbod_completion.lua:39: in function 'complete'
        ...re/nvim/site/pack/paqs/start/nvim-cmp/lua/cmp/source.lua:314: in function 'complete'
        ...hare/nvim/site/pack/paqs/start/nvim-cmp/lua/cmp/core.lua:289: in function 'complete'
        ...hare/nvim/site/pack/paqs/start/nvim-cmp/lua/cmp/core.lua:169: in function 'callback'
        ...hare/nvim/site/pack/paqs/start/nvim-cmp/lua/cmp/core.lua:219: in function 'autoindent'
        ...hare/nvim/site/pack/paqs/start/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'
        ...hare/nvim/site/pack/paqs/start/nvim-cmp/lua/cmp/init.lua:312: in function 'callback'
        .../site/pack/paqs/start/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        .../site/pack/paqs/start/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <.../site/pack/paqs/start/nvim-cmp/lua/cmp/utils/autocmd.lua:22>
```

Here is how I have configured autocompletion for SQL:

```lua
cmp.setup.filetype("sql", {
	view = {
		entries = "native",
	},
	snippet = {
		expand = function(args)
		    require("luasnip").lsp_expand(args.body)
		end,
	},
	mapping = cmp.mapping.preset.insert({
		["<C-d>"] = cmp.mapping.scroll_docs(-4),
		["<C-f>"] = cmp.mapping.scroll_docs(4),
		["<C-Space>"] = cmp.mapping.complete(),
		["<C-e>"] = cmp.mapping.close(),
		["<CR>"] = cmp.mapping.confirm({ select = true }),
	}),
	sources = cmp.config.sources(
		{ { name = "vim-dadbod-completion" }, { name = "luasnip" } },
		{ { name = "buffer" } }
	),
})
```

I am likely doing something wrong, but this used to work until quite recently. Other completion sources appear to be working fine, as far as I can tell.

I am using Neovim 0.8.0, and nvim-cmp commit aee40113c2ba3ab158955f233ca083ca9958d6f8

**Comment by kristijanhusak** [comment]
Unfortunately, I'm not able to reproduce this.
Since I'm trying to isolate the issue, can you try this?

* Remove cmp setup completely
* Open up an sql file
* Run this command: `:setlocal omnifunc=vim_dadbod_completion#omni`
* Type something, like `TableN`, and press `<C-x><C-o>` to trigger omnifunc completion

Do you still get an error? If yes, please post the stack trace.
Also, let me know which database type are you using.

**Comment by bowmanjd** [comment]
Thank you for these tips! I have done what you suggest. Upon pressing `<C-x<C-o>` I receive the following:

```
E730: using List as a String
-- Omni completion (^O^N^P) Pattern not found
```

**Comment by kristijanhusak** [comment]
> But I should point out that this is only when autocompleting columns


Thanks, this is very helpful.

Since there is no any stacktrace, could you please run `:set debug=msg` in command line before trying `<C-x><C-o>` again?

Also, can you try pulling latest changes from master and see if issue is maybe resolved?

**Comment by kristijanhusak** [comment]
No worries, I actually did find and fix a few bugs from this issue, so it was useful.
