### ISSUE TITLE
Completions getting inserted wrapped in ""

### ISSUE THREAD

**Issue by igorgue** [kristijanhusak/vim-dadbod-completion#43]
Hi, thank you for such cool plugin.

I have a problem, I use `nvim-cmp` with the config:

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "sql", "mysql", "plsql", "redis" },
    callback = function()
        cmp.setup.buffer({ sources = { { name = "vim-dadbod-completion" } } })
    end,
})
```

And currently when I pick the completion suggested by this plugin only it wraps it in `"`"

![image](https://user-images.githubusercontent.com/7014/206549186-df2f9532-eab1-4bcd-9427-9fbd2398651f.png)

**Comment by kristijanhusak** [comment]
Should be fixed now, thanks for reporting.

**Comment by igorgue** [comment]
Perfect! Thank you so much!
