### ISSUE TITLE
suggestions for columns fetched but not being suggested

### ISSUE THREAD

**Issue by SebastianBehrens** [kristijanhusak/vim-dadbod-completion#50]
I have two databases. For one database column names are being suggested as expected. For the other they are not.

I found [this ](https://github.com/kristijanhusak/vim-dadbod-completion/issues/3)issue, where I tried [this ](https://github.com/kristijanhusak/vim-dadbod-completion/issues/3#issuecomment-619880683) query.
The query finishes in SQL Server in 00:00:00s (rounded I guess)

I also checked the troubleshoot [here](https://github.com/kristijanhusak/vim-dadbod-completion/issues/3#issuecomment-620788894)
which results in the following
![image](https://github.com/kristijanhusak/vim-dadbod-completion/assets/51058351/76bef33b-16ea-46fd-9f32-1d8ad92f6c26)

Since everything works with other databases, but the one in question, even when I remove all other databases from the[ configuration in the vimrc](https://github.com/kristijanhusak/vim-dadbod-ui#via-gdbs-global-variable), I think the config to the database is fine.

I attached the logs (gotten via profile func *).
Can I try something else?

[dbui_bug.log](https://github.com/kristijanhusak/vim-dadbod-completion/files/12037149/dbui_bug.log)
[dbui_working.log](https://github.com/kristijanhusak/vim-dadbod-completion/files/12037151/dbui_working.log)

**Comment by SebastianBehrens** [comment]
Edit: Even the alias is being correctly parsed and suggested on the go. It is just the column names (for that specific database).

**Comment by SebastianBehrens** [comment]
[good.log](https://github.com/kristijanhusak/vim-dadbod-completion/files/12042836/good.log)
[bad.log](https://github.com/kristijanhusak/vim-dadbod-completion/files/12042840/bad.log)
These logs are maybe a bit more specific, as I started profiling right before the database connection and typed similar stuff, so less overhead or irrelevant plugins in log.
(I presume the third party apps are irrelevant, as the issue persists even if only coc.nvim, vim-dadbod, vim-dadbod-ui and vim-dadbod-completion are loaded)

**Comment by SebastianBehrens** [comment]
Update:
Found the issue: It was the condition to only fetch and cache columns if the total column count was less than 10k ([here](https://github.com/kristijanhusak/vim-dadbod-completion/blob/fc7321a17f4c55db11fae89a884ddf4724020bae/autoload/vim_dadbod_completion.vim#L280)).

My database had ~12k columns.
I upped it now to 30k. In my naïveté, I suppose this cannot break the setup.
At most, it might slow things down, is that right?

Once again, thank you from the bottom of my heart for having made this! It makes my sql-life so much better!

**Comment by kristijanhusak** [comment]
> For one database column names are being suggested as expected. For the other they are not

Are you not getting suggestions at that moment or not at all? Try this:

1. Leave only that single DB in the configuration
2. Open up new query for that DB
3. Try typing in something to trigger fetching the completion. Assuming you have `users` table, try somethign like this:
```sql
select * from users where users.
```
At this moment, you should get those messages you sent on screenshot, and completion should appear automatically.
If it does not appear automatically, try removing `users.` part from the query and try typing it again to trigger the completion. Does that make it work?

At first I thought this is some issue with CoC ,but I gave it a quick test locally and it works fine for me.

Which database type are you working with?

**Comment by SebastianBehrens** [comment]
On the database with the many columns, I got suggestions for tables (aliases), databases, but not columns.
But as I said, the issue was in the condition [here](https://github.com/kristijanhusak/vim-dadbod-completion/blob/fc7321a17f4c55db11fae89a884ddf4724020bae/autoload/vim_dadbod_completion.vim#L280), so I just changed that.
Should one maybe mention that in the docs?

**Comment by kristijanhusak** [comment]
That number should not be changed. The idea is to lazy load columns to avoid blocking the UI. I cannot help without being able to reproduce the issue.

**Comment by SebastianBehrens** [comment]
I see.
I used an mssql database with more than 10k total columns in the database.
