### ISSUE TITLE
nvim-cmp stops working when having vim-dadbod-completion installed

### ISSUE THREAD

**Issue by Napam** [kristijanhusak/vim-dadbod-completion#53]
I am using LunarVim (which again uses nvim-cmp), with Neovim 0.9.1. I am installing the plugin using Lazy.

Just by having this plugin installed I lose all my code autocompletion. Things looks right when I do LspInfo (all the language servers are connected). 

There is nothing different in the LspLog when having the plugin installed or not.

My config is basically:

```lua
lvim.plugins = {
  {
    "kristijanhusak/vim-dadbod-ui",
    dependencies = { "tpope/vim-dadbod", "kristijanhusak/vim-dadbod-completion"}
  }
}

vim.api.nvim_create_autocmd(
  "FileType",
  { pattern = { "dbui" }, command = ":nmap <buffer> l <Plug>(DBUI_SelectLineVsplit)" }
)

vim.api.nvim_create_autocmd("FileType", {
  pattern = { "sql", "mysql", "plsql" },
  command = ":lua require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })",
})
```

**Comment by Zethtren** [comment]
I have also had this issue. 

```lua
return {
  {
    "tpope/vim-dadbod",
    dependencies = {
      "kristijanhusak/vim-dadbod-ui",
    },
  },
  {
    "kristijanhusak/vim-dadbod-ui",
  },
  -- {
  --   "kristijanhusak/vim-dadbod-completion",
  -- },
}
```

Commenting and uncommenting this line toggles the issue. 

I am using LazyVim and my nvim-cmp config is completely default apart from a slight style choice.

```lua
return {
  {
    "hrsh7th/nvim-cmp",
    lazy = true,
    opts = function(_, opts)
      local cmp = require("cmp")
      opts.completion = {
        completeopt = "menu,menuone,noinsert",
      }
      opts.window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      }
      return opts
    end,
  },
}
```

I would love this behavior inside of SQL editors but this just disables it globally for me. 

I notice a strange behavior where it seems that nvim-cmp loading gets placed "behind" dadbod-completion when it is active. 

```
-- `:Lazy profile` with dadbod-completion
      ➜  after 5.14ms
        ★   after/plugin/vim_dadbod_completion.lua 5.06ms
          ‒   nvim-cmp 4.53ms
            ●   crates.nvim 2.32ms
            ●   copilot-cmp 0.53ms
              ➜   copilot.lua 0.46ms
                ★   copilot.lua/plugin/copilot.lua 0.03ms
            ●   cmp-nvim-lsp 0.04ms
            ●   cmp-buffer 0.08ms
            ●   cmp-path 0.06ms
            ●   cmp_luasnip 0.07ms
            ●   nvim-cmp/plugin/cmp.lua 0.26ms
        ★   after/plugin/vim_dadbod_completion.vim 0.02ms

```
and removed from "InsertEnter" where I normally see it. 
I'm not sure if the extension is taking ownership and overwriting the "event" somewhere. But something along those lines is what the behavior seems to suggest.

```
-- `:Lazy profile` without dadbod-completion
InsertEnter 21.42ms
      ➜   nvim-cmp 21.31ms
        ★   crates.nvim 10.62ms
          ‒   after/plugin/cmp_crates.lua 0.69ms
        ★   copilot-cmp 3ms
          ‒   copilot.lua 2.67ms
            ●   copilot.lua/plugin/copilot.lua 0.18ms
        ★   cmp-buffer 5.08ms
          ‒   after/plugin/cmp_buffer.lua 4.95ms
        ★   cmp-path 0.57ms
          ‒   after/plugin/cmp_path.lua 0.47ms
        ★   cmp_luasnip 0.66ms
          ‒   after/plugin/cmp_luasnip.lua 0.6ms
        ★   nvim-cmp/plugin/cmp.lua 0.27ms
```

**Comment by Zethtren** [comment]
I noticed that my dependencies might have caused some confusion. dadbod requiring ui instead of the other way around.

I will invert these tomorrow and see if that fixes the issue on my end.

I tried reviewing all of the places where this extension interacts with cmp and nothing stood out as being a potential cause. 

I will let you know if this corrects the behavior or if I find anything else.

**Comment by kristijanhusak** [comment]
I'm also using Lazy. You can try my setup. Here's how I set up dadbod related stuff: https://github.com/kristijanhusak/neovim-config/blob/master/nvim/lua/partials/plugins/db.lua

And this is where I set up cmp for it: https://github.com/kristijanhusak/neovim-config/blob/master/nvim/lua/partials/plugins/completion.lua#L93-L106

**Comment by Zethtren** [comment]
Thanks! It was not having the "cmd" line in my case. Apart from changing vsnip to luasnip copy pasting the second worked like a charm as well. 

Reference solution for anyone else using LazyVim that finds this issue. 

Thanks for the help and the great applications! @kristijanhusak 
Keep up the great work!

```lua
-- plugins/cmp.lua
return {
  {
    "hrsh7th/nvim-cmp",
    lazy = true,
    opts = function(_, opts)
      local cmp = require("cmp")
      opts.completion = {
        completeopt = "menu,menuone,noinsert",
      }
      opts.window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      }
      return opts
    end,
  },
}
```

```lua
-- plugins/dadbod.lua
return {
  {
    "kristijanhusak/vim-dadbod-ui",
    dependencies = {
      { "tpope/vim-dadbod", lazy = true },
      { "kristijanhusak/vim-dadbod-completion", lazy = true, ft = { "sql", "mysql", "plsql" } },
    },
    cmd = { "DBUI", "DBUIFindBuffer" },
  },
}
```

**Comment by Napam** [comment]
@kristijanhusak Thank you very much for the help. For me the solution was a little weird. I kept my code just the same, but the only thing I added was `local cmp = require("cmp")` (could be before or after the autocommand). That is, my code is this at the moment:

```lua
vim.api.nvim_create_autocmd("FileType", {
	pattern = { "sql", "mysql", "plsql" },
	command = ":lua require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })",
})

local cmp = require("cmp")
```

I don't understand why requiring `cmp` as a local config variable solves anything. Doing this alone for example won't work:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "sql", "mysql", "plsql" },
  callback = function()
    require("cmp").setup.buffer({
      sources = {
        { name = "vim-dadbod-completion" },
        { name = "buffer" },
        { name = "luasnip" },
      },
    })
  end,
})
```

To make it work I MUST require `cmp` at some point in the code, for example:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "sql", "mysql", "plsql" },
  callback = function()
    require("cmp").setup.buffer({
      sources = {
        { name = "vim-dadbod-completion" },
        { name = "buffer" },
        { name = "luasnip" },
      },
    })
  end,
})

require("cmp") -- must have this
```

Maybe it is because LunarVim is doing something funny with cmp? I don't feel it is because of that, but at least this fixed my issue.

Either way, thanks for the great plugins @kristijanhusak. They work really well.

**Comment by kristijanhusak** [comment]
I'm closing this since it seems that everyone managed to solve the configuration issue.

**Comment by fredrikaverpil** [comment]
Does anyone here know if it's possible to _extend_ the setup of the current buffer rather than hardcode it with `cmp.setup.buffer()`?

For example, with global cmp sources, you can use something like this:

```lua
local cmp =require("cmp")
local current_config = cmp.get_config()
local dadbod_completion_source = { name = "vim-dadbod-completion" }

table.insert(current_cmp_config.sources, dadbod_completion_source)
```

But that will affect all buffers, not only the current (sql) buffer.

**Comment by kristijanhusak** [comment]
@fredrikaverpil this is how I set up dadbod completion only for sql buffers:

https://github.com/kristijanhusak/neovim-config/blob/master/nvim/lua/partials/plugins/completion.lua#L93C1-L106

I'm not sure how could you extend. Maybe extract the defaults you want to extend into separate variable and just use them both for SQL buffers.

**Comment by fredrikaverpil** [comment]
@kristijanhusak hey 👋  yeah that might be a good solution.

Looks like this works: https://github.com/fredrikaverpil/dotfiles/blob/eef23ab2c1101242eba24c3a4cb02de35074520f/nvim-lazyvim/lua/plugins/sql.lua#L41-L64

**Comment by asfaltboy** [comment]
I just came across it, when naively adding completions with the config explained in the README. I'm trying @fredrikaverpil example config above

How do you feel about an update to the README to include one of the above solutions (ideally the simplest one), otherwise future users of nvim-cmp will see the same results...
