### ISSUE TITLE
Autocompletion Issue in Large MSSQL Databases

### ISSUE THREAD

**Issue by juancarlis** [kristijanhusak/vim-dadbod-completion#57]
Hello,

I'm encountering an issue with the vim-dadbod-completion plugin when working with large MSSQL Server databases. Specifically, the autocompletion feature for database columns is not functioning as expected.

### Issue Description:
When attempting to write SQL queries in Neovim, the column autocompletion feature does not trigger after typing a period following a table alias. This issue seems to be particularly prevalent in larger databases. For example, I've noticed this behavior in a database with over 12,000 columns and 1,150 tables. The autocompletion fails to fetch column names, hindering the workflow.

### Steps to Reproduce:
1. Connect to a large MSSQL Server database using vim-dadbod-completion.
2. Write a query such as `SELECT TOP 10 * FROM some_table st WHERE st.`.
3. After typing the period following the table alias (`st.`), expect column names to be suggested, but no suggestions appear.

### Expected Behavior:
The plugin should provide a list of column names for autocompletion after typing the period following a table alias.
This issue does not seem to occur with smaller databases.

I would appreciate any guidance or suggestions on resolving this issue. Is there a configuration setting that I might be missing, or is this a known limitation with larger databases?

This is my current setting:

```lua
return {
	'kristijanhusak/vim-dadbod-ui',
  dependencies = {
    'tpope/vim-dadbod',
    'tpope/vim-dotenv',
    { "kristijanhusak/vim-dadbod-completion", ft = { "sql", "mysql", "plsql"}, lazy = true },
  },
  cmd = {
      "DBUI",
      "DBUIToggle",
      "DBUIAddConnection",
      "DBUIFindBuffer",
  },

  init = function()
    vim.g.db_ui_use_nerd_fonts = 1
    vim.g.db_ui_show_database_icon = 1
    -- vim.g.db_ui_force_echo_notifications = 1
    vim.g.db_ui_win_position = 'left'
    vim.g.db_ui_winwidth = 30


    -- opening it in a new tab
    vim.keymap.set('n', '<leader><leader>db', ':tab DBUI<cr>', {})

    -- just close the tab, but context related of the keybinding
    vim.keymap.set('n', '<leader><leader>tq', ':tabclose<cr>')

    vim.api.nvim_create_autocmd("FileType", {
      pattern = "sql",
      callback = function()
          vim.bo.omnifunc = "vim_dadbod_completion#omni"
      end,
    })
  end,
}
```

Thank you for your assistance and for the great work on this plugin.

**Comment by kristijanhusak** [comment]
Does it work when you do not use the alias? For example:

```sql
SELECT TOP 10 * FROM some_table WHERE some_table.
```

**Comment by juancarlis** [comment]
Only in a small MSSQL Database that we have for testing. It works with and without the alias. 
On the productive database (with the 1150 tables) it does not.

**Comment by kristijanhusak** [comment]
There was a similar issue reported here https://github.com/kristijanhusak/vim-dadbod-completion/issues/50. Can you try updating [this number](https://github.com/kristijanhusak/vim-dadbod-completion/blob/master/autoload/vim_dadbod_completion.vim#L280) locally to 20000 and see if that helps?

**Comment by juancarlis** [comment]
Yes, I already tried that, but it didn't work. So, I started thinking that I was lacking something in my configuration, but I couldn't find anything yet

**Comment by kristijanhusak** [comment]
Did you set a number that is bigger than the actual columns count? I suggested 20000 because you wrote it has over 12000 columns, but maybe it's even bigger than that. Try some crazy number like 200000 or so just for testing purposes.

**Comment by juancarlis** [comment]
I tried with 15000, 30000, and now 200000 but nothing.

**Comment by kristijanhusak** [comment]
I'm not an active MSSQL user, and unfortunately, I don't have access to any DB that is that big. 
Do you have the same permissions on both small and big DB? Is there a chance that you are not allowed to access `information_schema.columns` on the big DB? 

Do you get tables completion in the big DB?

Try printing out the results somewhere around [here](https://github.com/kristijanhusak/vim-dadbod-completion/blob/bcdf3ff768cc7e544a0f78b0383d8719c2116569/autoload/vim_dadbod_completion.vim#L286) and see if the format of the results is the same for both small and big DB.

**Comment by juancarlis** [comment]
Thanks for the help, I could find out the issue.
When printing the cached columns I realized that I was not getting data from cached columns. 
For some reason that database does not want the information_schema queries to be set in lower case, so I changed the queries in [here](https://github.com/kristijanhusak/vim-dadbod-completion/blob/bcdf3ff768cc7e544a0f78b0383d8719c2116569/autoload/vim_dadbod_completion/schemas.vim#L1C1-L1C1) by setting every `information_schema.columns` to `INFORMATION_SCHEMA.COLUMS` and now works perfectly.

Also I set the max number of columns up to 15000. 

Thanks again for making this project and taking time on responding!

**Comment by kristijanhusak** [comment]
That's strange. SQL should be case insensitive. If you put information_schema.columns in uppercase, and return the `columns` to 10000, does it work?

**Comment by juancarlis** [comment]
At first my thinking was that MSSQL was case sensitive because I was having this kind of problems since I started with MSSQL at this job, but now trying to solve this completion issue I found this other MSSQL DB (the smallest one with 93 tables) that doesn't mind information_schema in lower case. So I'm kind of confused with this.

I changed the columns to 10000 and it worked. I'm gonna leave it like this, so as to change the source code as less as possible, but I don't know if there is gonna be any issues with some tables, cause the size of this schema bigger than the 10k columns.

**Comment by kristijanhusak** [comment]
Does `INFORMATION_SCHEMA.COLUMNS` work in the small database? If yes, I guess we could just default to uppercase for everything.

**Comment by juancarlis** [comment]
Yes it works.

**Comment by kristijanhusak** [comment]
I pushed a change where I uppercased the table and column names. Can you pull latest changes and check if it works?

**Comment by juancarlis** [comment]
Pulled and working. 
Thx for the help!
