### ISSUE TITLE
Editor becomes unresponsive when completing materialized view columns

### ISSUE THREAD

**Issue by peteryates** [kristijanhusak/vim-dadbod-completion#6]
This is pretty niche and is probably more to do with PostgreSQL's `information_schema` not working in the most predictable manner, but here's what happens.

I have a [materialized view](https://github.com/DFE-Digital/gias-query-tool/blob/master/ddl/views/open_schools.sql) in [this project](https://github.com/DFE-Digital/gias-query-tool) and when attempting to list its columns, eg

```sql
select os.<something> from open_schools os;
```
The following message flickers in the command line bar in vim.

```
[dadbod completion] Fetching columns for table open_schools... Done
```

Looking at `pg_stat_activity` it's running this repeatedly.

```
select table_name,column_name from information_schema.columns where table_name='open_schools'
```
This always returns nothing because materialized view columns won't show up in `information_schema.columns`. Before this I would totally have expected they would.

I think not offering completion when it's a materialized view is an acceptable solution really. Looking at the generated queries to produce the output from `\d+ open_schools` (via `psql -E` to show hidden queries) it's pretty hairy and very PostgreSQL-specific.

Again, more than happy to assist if I can. I'll have a look today to see if there's a simpler way of querying columns of a materialized view via the information schema.

**Comment by kristijanhusak** [comment]
I pushed a fix where results defaults to empty array if there are no found columns, which is the case for the materialized view. This should prevent doing fetching more than once. Give it a test and let me know if it works.

**Comment by peteryates** [comment]
Worked perfectly. Thanks again :+1:
