### ISSUE TITLE
MariaDB columns completion doesn't work

### ISSUE THREAD

**Issue by Praczet** [kristijanhusak/vim-dadbod-completion#65]
Hi, 

I am using vim-dadbod, vim-dadbod-ui and vim-dadbod-completion with LazyVim.

In MariaDB  query I do not have columns:

SO when I `SELECT * FROM ` I have completion for tables

![image](https://github.com/kristijanhusak/vim-dadbod-completion/assets/109667910/80507bae-156a-408a-8daf-9cd058460abc)

but list of columns doesn't exists..

I have Added manually table helpers for MariaDB (in vim-dadbod-ui are not added by defaults) but still I can not make completion to work.

Can you tell me if it is possible to have completion working with MariaDB.

P.S.
For SQLite column completion works

**Comment by kristijanhusak** [comment]
Does this query work for you?

```sql
SELECT TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
```

**Comment by Praczet** [comment]
> Does this query work for you?
> 
> ```sql
> SELECT TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
> ```

Yes, 

It does work

**Comment by kristijanhusak** [comment]
Do you get completion on columns after the table name? For example:

```sql
select * from help where help.column_name_here
```

**Comment by Praczet** [comment]
> Do you get completion on columns after the table name? For example:
> 
> ```sql
> select * from help where help.column_name_here
> ```

no.

**Comment by kristijanhusak** [comment]
Is the database big, in terms, does it have more than 10k columns? You can check that with this:

```sql
SELECT COUNT(*) AS total FROM INFORMATION_SCHEMA.COLUMNS
```

**Comment by kristijanhusak** [comment]
Is the database big, in terms, does it have more than 10k columns? You can check that with this:

```sql
SELECT COUNT(*) AS total FROM INFORMATION_SCHEMA.COLUMNS
```

**Comment by Praczet** [comment]
> ```sql
> SELECT COUNT(*) AS total FROM INFORMATION_SCHEMA.COLUMNS
> ```

The simple answer is **no**

The result of that query is `5.613` I takes number of rows for all databases in  server...

I mean if I narrow down it to one database like this:

```sql
SELECT
    COUNT(*) AS total
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE 
  TABLE_SCHEMA = 'mydatabase'
```
I have 300 rows

**Comment by kristijanhusak** [comment]
Can you try importing the example db from here https://www.mariadbtutorial.com/getting-started/mariadb-sample-database/ and see if it works? I cannot reproduce it with this db.

**Comment by Praczet** [comment]
BTW: 
Maybe it is related  or not, but I've changed a little bit *table helpers* to have them in mariadb.
Here is my config:
```lua
      vim.g.db_ui_table_helpers = {
        mariadb = {
          List = "SELECT * from {optional_schema}`{table}` LIMIT 200",
          Columns = "DESCRIBE {optional_schema}`{table}`",
          Indexes = "SHOW INDEXES FROM {optional_schema}`{table}`",
          ForeignKeys = "SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = '{dbname}' AND TABLE_NAME = '{table}' AND CONSTRAINT_TYPE = 'FOREIGN KEY'",
          PrimaryKeys = "SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = '{dbname}' AND TABLE_NAME = '{table}' AND CONSTRAINT_TYPE = 'PRIMARY KEY'",
          Unique = "SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = '{dbname}' AND TABLE_NAME = '{table}' AND CONSTRAINT_TYPE = 'UNIQUE'",
        },
      }
```

**Comment by Praczet** [comment]
hi,
Completion  works. Thnx

Only two things that I am not sure if should work like this.

## 1
When I am adding a connection to the specific database.  I can see in schemas all databases.

For example in my local server I have database1. database2, database3

My connection:

`mariadb://user:passwrod@localhost/database1`

but still I see in Schemas all databases :
- database1
- database2
- database3

If it should work like this  it is ok... I can live with it. 

## 2
There is still not table helpers by default...  This is no problem since it is easy to add them in config..


Thank you very much for completion... It is really nice to have so fast response.

I like your plugin very much

**Comment by kristijanhusak** [comment]
@Praczet I fixed both of those issues, but those are related to vim-dadbod-ui. Do a plugin updates and it should be fixed.

**Comment by Praczet** [comment]
Yea, 
I've just checked :-D.
It works perfectly!
Thank you.

**Comment by Herz3h** [comment]
I have latest of every dadbod plugin, and it doesn't suggest any column in my case:

I've tried `mysql://` and `mariadb://` scheme, with or without password, tested with the sample nation database

`mysql://root:password@localhost/nation`

Also tested without specifying the database in the connection url. Doesn't work any better.

I'm using the suggested config (**dadbod completion + blink.cmp**, tried **dadbod completion + coq_nvim** before, same)

MariaDB 10.11.9 on OSX and neovim 0.10.2

**Comment by kristijanhusak** [comment]
@Herz3h do you get some autocompletion, like tables, reserved words, etc?
Can you also test `omnifunc` completion?

**Comment by Herz3h** [comment]
I get databases, tables, and reserved words, but no columns. As state before, I already tested omnifunc, same behavior: no columns @kristijanhusak

**Comment by Herz3h** [comment]
@kristijanhusak Just tested with a postgres public db https://rnacentral.org/help/public-database and same behavior, no autocomplete of column

**Comment by kristijanhusak** [comment]
I'm getting autocompletion with that public database so this must be a configuration issue.
Can you provide your vim-dadbod setup so we can check? Also, some system information and some queries that you are testing would be very helpful.
