### ISSUE TITLE
psql command outputs aren't displayed correctly

### ISSUE THREAD

**Issue by Prajwalg19** [kristijanhusak/vim-dadbod-completion#66]
Executing psql commands like `\d` or `\l` doesn't display the output in the output buffer properly. It looks something like this

![image](https://github.com/kristijanhusak/vim-dadbod-completion/assets/93521144/a097b1ca-cbf5-4e6c-90f1-6ddf2449352f)

which should instead look like this 

![image](https://github.com/kristijanhusak/vim-dadbod-completion/assets/93521144/b5f5669c-6dab-4352-b2b8-f0c0f7e1dd96)

Moving the cursor around in the output buffer will correct the output but i need switch to the output buffer and move the cursor around for every psql command i execute. 

Note: This happens only for the psql commands not for the postgres database query commands.

**Comment by kristijanhusak** [comment]
This issue does not belong here, and is not an issue in first place. It's folding.

See https://github.com/kristijanhusak/vim-dadbod-ui/pull/203
