### ISSUE TITLE
Unable to get completions

### ISSUE THREAD

**Issue by anihm136** [kristijanhusak/vim-dadbod-completion#7]
Hi. I'm using vim-dadbod and this plugin (through coc-db), and I'm not able to get completion candidates through the plugin. Dadbod works fine for executing queries. How can I debug this?
I'm setting the variable `b:db` after the buffer loads using dadbod, not through an autocmd. Could that be the reason?
Thanks in advance.

**Comment by kristijanhusak** [comment]
Problem was that cache wasn't refreshed after you set the variable. Do an update and give it another test, should be working fine now.
