### ISSUE TITLE
vim-dadbod-completion coming up on `:CmpStatus' but not giving any suggestions

### ISSUE THREAD

**Issue by BenjyRead** [kristijanhusak/vim-dadbod-completion#75]
Trying to get the dadbod ***trilogy*** working, and its all working fine except for this plugin which seemingly isn't giving any suggestions even though its on `:CmpStatus`

Here is all my nvim-cmp/dadbod code in my init.lua:

(lazy.nvim)
```lua
    {
        "hrsh7th/nvim-cmp",
        dependencies = {
            -- Snippet Engine & its associated nvim-cmp source
            "L3MON4D3/LuaSnip",
            "saadparwaiz1/cmp_luasnip",

            -- source path
            "hrsh7th/cmp-path",

            -- Adds LSP completion capabilities
            "hrsh7th/cmp-nvim-lsp",

            -- Adds buffer completion capabilities
            "hrsh7th/cmp-buffer",

            -- Adds a number of user-friendly snippets
            "rafamadriz/friendly-snippets",
        },
    },
```
```lua
    {
        'tpope/vim-dadbod',
        lazy = true,
    },
    {
        'kristijanhusak/vim-dadbod-ui',
        dependencies = {
            { 'tpope/vim-dadbod',                     lazy = true },
            { 'kristijanhusak/vim-dadbod-completion', ft = { 'sql', 'mysql', 'plsql' }, lazy = true }, -- Optional
        },
        cmd = {
            'DBUI',
            'DBUIToggle',
            'DBUIAddConnection',
            'DBUIFindBuffer',
        },
        init = function()
            -- Your DBUI configuration
            vim.g.db_ui_use_nerd_fonts = 1
        end,
    }
```

additional settings:
```lua
-- [[ Configure nvim-cmp ]]
-- See `:help cmp`

local cmp = require("cmp")
local luasnip = require("luasnip")

require("luasnip.loaders.from_vscode").lazy_load()
luasnip.config.setup({})

cmp.setup({

    snippet = {
        expand = function(args)
            luasnip.lsp_expand(args.body)
        end,
    },

    completion = {
        completeopt = "menu,menuone,noinsert",
    },

    --TODO: not a clue what this does but it's important
    mapping = cmp.mapping.preset.insert({

        ["<C-n>"] = cmp.mapping.select_next_item(),
        ["<C-p>"] = cmp.mapping.select_prev_item(),
        ["<C-d>"] = cmp.mapping.scroll_docs(-4),
        ["<C-f>"] = cmp.mapping.scroll_docs(4),
        ["<C-Space>"] = cmp.mapping.complete({}),

        ["<CR>"] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
        }),

        ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_next_item()
            elseif luasnip.expand_or_locally_jumpable() then
                luasnip.expand_or_jump()
            else
                fallback()
            end
        end, { "i", "s" }),

        ["<S-Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_prev_item()
            elseif luasnip.locally_jumpable(-1) then
                luasnip.jump(-1)
            else
                fallback()
            end
        end, { "i", "s" }),
    }),

    sources = {
        { name = "nvim_lsp" },
        { name = "luasnip" },
    },

})

-- nvim-cmp settings for sql completion (100% stolen from TJ)

cmp.setup.filetype({ "sql" }, {
    sources = {
        { name = "vim-dadbod-completion" },
        { name = "buffer" }, -- Use buffer source for path completion
    }
})
```
![image](https://github.com/user-attachments/assets/c9d97e54-a0ef-4b3b-b693-83922e560c2b)

NOTE: im a bit of a noob when it comes to neovim so it might be a really dumb issue im not seeing

My full config -> [https://github.com/BenjyRead/nvim-config](https://github.com/BenjyRead/nvim-config)

**Comment by kristijanhusak** [comment]
Which DB are you using? And is vim-dadbod-ui working fine, in terms of showing the tables, schemas, etc?

**Comment by BenjyRead** [comment]
> Which DB are you using? And is vim-dadbod-ui working fine, in terms of showing the tables, schemas, etc?

MariaDB, and in this example it was just a recently created empty db on localhost

**Comment by kristijanhusak** [comment]
Are you able to test with another db type, like postgres?

Also, can you try commenting out the filetype part (last 6 lines), and add `{ name = "vim-dadbod-completion" }` to the sources above?

I don't see anything wrong in your config, but if dadbod-ui works, it is probably something small.

**Comment by kristijanhusak** [comment]
Ah ok, I think I know what it is. Try creating an empty buffer from your dadbod-ui connection, and see if it works from there. It should.
This is because everything is lazy loaded through `DBUI` command.
I see that your buffer is `messingaround.sql`, so the file does not now from where to autocomplete. I'm not sure how you set up a connection, but to work  in this case you need to have `g:db` (or vim.g.db in lua) set up with a default connection.

**Comment by BenjyRead** [comment]
> Ah ok, I think I know what it is. Try creating an empty buffer from your dadbod-ui connection, and see if it works from there. It should. This is because everything is lazy loaded through `DBUI` command. I see that your buffer is `messingaround.sql`, so the file does not now from where to autocomplete. I'm not sure how you set up a connection, but to work in this case you need to have `g:db` (or vim.g.db in lua) set up with a default connection.
> 
> Edit: Also, remove the `cmd` part and add `event = 'VeryLazy'` instead, to properly load DBUI when the neovim is loaded.

Sorry about the screenshot showing an SQL file instead of the query buffer it was a mistake. It still is not working on the query buffer.


```lua
    {
        'kristijanhusak/vim-dadbod-ui',
        dependencies = {
            { 'tpope/vim-dadbod',                     lazy = true },
            { 'kristijanhusak/vim-dadbod-completion', ft = { 'sql', 'mysql', 'plsql' }, lazy = true }, -- Optional
        },
        -- cmd = {
        --     'DBUI',
        --     'DBUIToggle',
        --     'DBUIAddConnection',
        --     'DBUIFindBuffer',
        -- },
        event = "VeryLazy",
        init = function()
            -- Your DBUI configuration
            vim.g.db_ui_use_nerd_fonts = 1
        end,
    }
```
was this the change you wanted me to make? The completions are still not working

**Comment by kristijanhusak** [comment]
Yes, try also removing lazy from both dependencies and add VeryLazy to them too.

It should work like this though but give that a try.

**Comment by BenjyRead** [comment]
```lua
    {
        'kristijanhusak/vim-dadbod-ui',
        dependencies = {
            { 'tpope/vim-dadbod',                     event = "VeryLazy" },                                   --lazy = true  },
            { 'kristijanhusak/vim-dadbod-completion', ft = { 'sql', 'mysql', 'plsql' }, event = "VeryLazy" }, -- lazy = true }, -- Optional
        },
        -- cmd = {
        --     'DBUI',
        --     'DBUIToggle',
        --     'DBUIAddConnection',
        --     'DBUIFindBuffer',
        -- },
        event = "VeryLazy",
        init = function()
            -- Your DBUI configuration
            vim.g.db_ui_use_nerd_fonts = 1
        end,
    }

```

this what your saying? still doesnt work :(

**Comment by kristijanhusak** [comment]
Try also removing the `ft` part. Also, did you manage to test some other db type?

**Comment by BenjyRead** [comment]
Im sorry I think I must have made a mistake at some point, because now when I do `:CmpStatus` it comes up as vim-dadbod-completion being unused 
![image](https://github.com/user-attachments/assets/abe3d3ce-407a-4d6c-8b0d-7d6b881b0592)

**Comment by BenjyRead** [comment]
You know this is going to seem really anti climactic and lame after all this, and thanks for being so patient helping me solve this. but adding nvim-dadbod-completion here:
```lua
sources = {
        { name = "nvim_lsp" },
        { name = "luasnip" },
    },
```lua
    sources = {
        { name = "nvim_lsp" },
        { name = "luasnip" },
        { name = "vim-dadbod-completion" },
    },
```
fixed it

**Comment by kristijanhusak** [comment]
I'm not sure how `cmp.buffer.filetype` works under the hood. You can also try this to use it only for sql files (this is what I use):

```lua
  vim.api.nvim_create_autocmd('FileType', {
    pattern = { 'sql', 'mysql', 'plsql' },
    callback = function()
      cmp.setup.buffer({
        sources = {
          { name = 'vim-dadbod-completion' },
          { name = 'vsnip' },
        },
      })
    end,
  })
```

Can we then close this?

**Comment by BenjyRead** [comment]
> Can we then close this?
Absolutely, thank you
