### ISSUE TITLE
"kind" field causing issue with blink.cmp

### ISSUE THREAD

**Issue by DanWlker** [kristijanhusak/vim-dadbod-completion#78]
Hi I'm not sure if this is the correct place to ask, but this is in relation to this issue:
https://github.com/Saghen/blink.cmp/issues/419

After some digging i noticed completions from dadbod is showing `kind = <table 2>`, which causes an issue when attempting to convert it to a lua table.

![image](https://github.com/user-attachments/assets/f758d463-b4e8-4a4a-9456-cede9f736e95)

 I'm not sure if its an issue with vim-dadbod-completion or blink. any pointers to perhaps resolve this would be appreciated. Thanks

![image](https://github.com/user-attachments/assets/fed79a3e-4bd0-4721-8bb4-b18acd68a7ef)

the for loop above avoids this error

**Comment by kristijanhusak** [comment]
I'm not really a user of blink.cmp, but maybe @joncrangle can help since he introduced it in https://github.com/kristijanhusak/vim-dadbod-completion/pull/76.

**Comment by joncrangle** [comment]
I think I'll need to submit a PR to change `require 'blink.cmp.types'.CompletionItemKind` to `require 'blink.cmp.types'.CompletionItemKind.Text` [here](https://github.com/kristijanhusak/vim-dadbod-completion/pull/76/files#diff-ab7574223aceeb1afeda17e163ae06e9b71720a5ba88015318281defb481206cR58). I won't be able to test this fix until later today though.

**Comment by DanWlker** [comment]
> I think I'll need to submit a PR to change `require 'blink.cmp.types'.CompletionItemKind` to `require 'blink.cmp.types'.CompletionItemKind.Text` [here](https://github.com/kristijanhusak/vim-dadbod-completion/pull/76/files#diff-ab7574223aceeb1afeda17e163ae06e9b71720a5ba88015318281defb481206cR58). I won't be able to test this fix until later today though.

fwiw, I tried this locally and it seems to be working

![image](https://github.com/user-attachments/assets/479a58e4-608c-4111-a6ab-27b14a4874ec)

**Comment by DanWlker** [comment]
> I pushed a change that should update the behavior similar to cmp. Let me know if it works.

yup I just updated my dependencies and all seems good, thanks
